# Generated by Django 6.0 on 2025-12-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('WORK', 'Work'), ('STUDY', 'Study'), ('PERSONAL', 'Personal')], default='WORK', max_length=20),
        ),
    ]
